/**
 * SMWS蒸留所コード → 蒸留所名 マッピング
 *
 * コード体系:
 *   数字のみ (1〜165) : シングルモルト
 *   G + 数字          : グレーンウイスキー
 *   B + 数字          : バーボン / アメリカンウイスキー
 *
 * 各エントリの構造:
 *   en: 英語名（公式表記）
 *   ja: 日本語名（カタカナ表記）
 */

/** @typedef {{ en: string, ja: string }} Distillery */
/** @type {Record<string, Distillery>} */
const DISTILLERIES = {
  // ── シングルモルト (1–50) ──────────────────────────────
  "1":   { en: "Glenfarclas",              ja: "グレンファークラス" },
  "2":   { en: "Glenlivet",                ja: "グレンリベット" },
  "3":   { en: "Bowmore",                  ja: "ボウモア" },
  "4":   { en: "Highland Park",            ja: "ハイランドパーク" },
  "5":   { en: "Auchentoshan",             ja: "オーヘントッシャン" },
  "6":   { en: "Glen Deveron (Macduff)",   ja: "グレンデヴロン（マクダフ）" },
  "7":   { en: "Longmorn",                 ja: "ロングモーン" },
  "8":   { en: "Tamdhu",                   ja: "タムドゥー" },
  "9":   { en: "Glen Grant",               ja: "グレングラント" },
  "10":  { en: "Bunnahabhain",             ja: "ブナハーブン" },
  "11":  { en: "Tomatin",                  ja: "トマーティン" },
  "12":  { en: "Benriach",                 ja: "ベンリアック" },
  "13":  { en: "Dalmore",                  ja: "ダルモア" },
  "14":  { en: "Talisker",                 ja: "タリスカー" },
  "15":  { en: "Glenfiddich",              ja: "グレンフィディック" },
  "16":  { en: "Glenturret",               ja: "グレンタレット" },
  "17":  { en: "Scapa",                    ja: "スキャパ" },
  "18":  { en: "Inchgower",               ja: "インチガワー" },
  "19":  { en: "Glen Garioch",             ja: "グレンギリー" },
  "20":  { en: "Inverleven",               ja: "インバーレーブン" },
  "21":  { en: "Glenglassaugh",            ja: "グレングラッサ" },
  "22":  { en: "Glenkinchie",              ja: "グレンキンチー" },
  "23":  { en: "Bruichladdich",            ja: "ブルックラディ" },
  "24":  { en: "Macallan",                 ja: "マッカラン" },
  "25":  { en: "Rosebank",                 ja: "ローズバンク" },
  "26":  { en: "Clynelish",               ja: "クライヌリッシュ" },
  "27":  { en: "Springbank",               ja: "スプリングバンク" },
  "28":  { en: "Tullibardine",             ja: "タリバーディン" },
  "29":  { en: "Laphroaig",               ja: "ラフロイグ" },
  "30":  { en: "Glenrothes",              ja: "グレンロセス" },
  "31":  { en: "Isle of Jura",             ja: "アイル・オブ・ジュラ" },
  "32":  { en: "Edradour",                ja: "エドラダワー" },
  "33":  { en: "Ardbeg",                  ja: "アードベッグ" },
  "34":  { en: "Tamnavulin",              ja: "タムナヴーリン" },
  "35":  { en: "Glen Moray",              ja: "グレンマレイ" },
  "36":  { en: "Benrinnes",               ja: "ベンリネス" },
  "37":  { en: "Cragganmore",             ja: "クラガンモア" },
  "38":  { en: "Caperdonich",             ja: "ケイパードニック" },
  "39":  { en: "Linkwood",               ja: "リンクウッド" },
  "40":  { en: "Balvenie",               ja: "バルヴェニー" },
  "41":  { en: "Dailuaine",              ja: "デイルユーエン" },
  "42":  { en: "Tobermory (Ledaig)",     ja: "トバモリー（レダイグ）" },
  "43":  { en: "Port Ellen",             ja: "ポートエレン" },
  "44":  { en: "Craigellachie",          ja: "クレイゲラキ" },
  "45":  { en: "Dallas Dhu",             ja: "ダラスデュー" },
  "46":  { en: "Glenlossie",             ja: "グレンロッシー" },
  "47":  { en: "Benromach",              ja: "ベンロマック" },
  "48":  { en: "Balmenach",              ja: "バルメナック" },
  "49":  { en: "St. Magdalene",          ja: "セント・マグダレン" },
  "50":  { en: "Bladnoch",              ja: "ブラッドノック" },

  // ── シングルモルト (51–100) ────────────────────────────
  "51":  { en: "Bushmills",              ja: "ブッシュミルズ" },
  "52":  { en: "Old Pulteney",           ja: "オールドプルトニー" },
  "53":  { en: "Caol Ila",              ja: "カリラ" },
  "54":  { en: "Aberlour",              ja: "アベラワー" },
  "55":  { en: "Royal Brackla",         ja: "ロイヤルブラックラ" },
  "56":  { en: "Coleburn",              ja: "コールバーン" },
  "57":  { en: "Glen Mhor",             ja: "グレンモー" },
  "58":  { en: "Strathisla",            ja: "ストラスアイラ" },
  "59":  { en: "Teaninich",             ja: "ティーニニック" },
  "60":  { en: "Aberfeldy",             ja: "アバフェルディ" },
  "61":  { en: "Brora",                 ja: "ブローラ" },
  "62":  { en: "Glenlochy",             ja: "グレンロッキー" },
  "63":  { en: "Glentauchers",          ja: "グレントーカーズ" },
  "64":  { en: "Mannochmore",           ja: "マノックモア" },
  "65":  { en: "Imperial",              ja: "インペリアル" },
  "66":  { en: "Ardmore",               ja: "アードモア" },
  "67":  { en: "Banff",                 ja: "バンフ" },
  "68":  { en: "Blair Athol",           ja: "ブレアアソル" },
  "69":  { en: "Glen Albyn",            ja: "グレンアルビン" },
  "70":  { en: "Balblair",              ja: "バルブレア" },
  "71":  { en: "Glenburgie",            ja: "グレンバーギー" },
  "72":  { en: "Miltonduff",            ja: "ミルトンダフ" },
  "73":  { en: "Aultmore",              ja: "オルトモア" },
  "74":  { en: "North Port",            ja: "ノースポート" },
  "75":  { en: "Glenury Royal",         ja: "グレンユーリーロイヤル" },
  "76":  { en: "Mortlach",              ja: "モートラック" },
  "77":  { en: "Glen Ord",              ja: "グレンオード" },
  "78":  { en: "Ben Nevis",             ja: "ベンネヴィス" },
  "79":  { en: "Deanston",              ja: "ディーンストン" },
  "80":  { en: "Glen Spey",             ja: "グレンスペイ" },
  "81":  { en: "Glen Keith",            ja: "グレンキース" },
  "82":  { en: "Glencadam",             ja: "グレンカダム" },
  "83":  { en: "Convalmore",            ja: "コンヴァルモア" },
  "84":  { en: "Glendullan",            ja: "グレンダラン" },
  "85":  { en: "Glen Elgin",            ja: "グレンエルギン" },
  "86":  { en: "Glenesk",               ja: "グレンエスク" },
  "87":  { en: "Millburn",              ja: "ミルバーン" },
  "88":  { en: "Speyburn",              ja: "スペイバーン" },
  "89":  { en: "Tomintoul",             ja: "トミントール" },
  "90":  { en: "Pittyvaich",            ja: "ピティヴェイク" },
  "91":  { en: "Dufftown",              ja: "ダフタウン" },
  "92":  { en: "Lochside",              ja: "ロッホサイド" },
  "93":  { en: "Glen Scotia",           ja: "グレンスコシア" },
  "94":  { en: "Old Fettercairn",       ja: "オールドフェッターケアン" },
  "95":  { en: "Auchroisk (Singleton)", ja: "オークロイスク（シングルトン）" },
  "96":  { en: "Glendronach",           ja: "グレンドロナック" },
  "97":  { en: "Littlemill",            ja: "リトルミル" },
  "98":  { en: "Inverleven (Lomond)",   ja: "インバーレーブン（ローモンド）" },
  "99":  { en: "Glenugie",              ja: "グレンユーギー" },
  "100": { en: "Strathmill",            ja: "ストラスミル" },

  // ── シングルモルト (101–165) ───────────────────────────
  "101": { en: "Knockando",                        ja: "ノッカンドゥー" },
  "102": { en: "Dalwhinnie",                       ja: "ダルウィニー" },
  "103": { en: "Royal Lochnagar",                  ja: "ロイヤルロッホナガー" },
  "104": { en: "Glenburgie (Glencraig)",           ja: "グレンバーギー（グレンクレイグ）" },
  "105": { en: "Tormore",                          ja: "トーモア" },
  "106": { en: "Cardhu",                           ja: "カードゥー" },
  "107": { en: "Glenallachie",                     ja: "グレンアラヒー" },
  "108": { en: "Allt-a-Bhainne",                   ja: "オルタヴァイン" },
  "109": { en: "Miltonduff (Mosstowie)",            ja: "ミルトンダフ（モストウィー）" },
  "110": { en: "Oban",                             ja: "オーバン" },
  "111": { en: "Lagavulin",                        ja: "ラガヴーリン" },
  "112": { en: "Loch Lomond (Inchmurrin)",         ja: "ロッホローモンド（インチマリン）" },
  "113": { en: "Braeval (Braes of Glenlivet)",     ja: "ブレイヴァル（ブレイズ・オブ・グレンリベット）" },
  "114": { en: "Springbank (Longrow)",             ja: "スプリングバンク（ロングロウ）" },
  "115": { en: "Knockdhu (An Cnoc)",               ja: "ノックドゥー（アンノック）" },
  "116": { en: "Yoichi",                           ja: "余市" },
  "117": { en: "Cooley (unpeated)",                ja: "クーリー（ノンピート）" },
  "118": { en: "Cooley (peated)",                  ja: "クーリー（ピート）" },
  "119": { en: "Yamazaki",                         ja: "山崎" },
  "120": { en: "Hakushu",                          ja: "白州" },
  "121": { en: "Isle of Arran",                    ja: "アイル・オブ・アラン" },
  "122": { en: "Loch Lomond (Croftengea)",         ja: "ロッホローモンド（クロフテンギア）" },
  "123": { en: "Glengoyne",                        ja: "グレンゴイン" },
  "124": { en: "Miyagikyo",                        ja: "宮城峡" },
  "125": { en: "Glenmorangie",                     ja: "グレンモーレンジィ" },
  "126": { en: "Springbank (Hazelburn)",            ja: "スプリングバンク（ヘーゼルバーン）" },
  "127": { en: "Bruichladdich (Port Charlotte)",   ja: "ブルックラディ（ポートシャーロット）" },
  "128": { en: "Penderyn",                         ja: "ペンダーリン" },
  "129": { en: "Kilchoman",                        ja: "キルホーマン" },
  "130": { en: "Chichibu",                         ja: "秩父" },
  "131": { en: "Hanyu",                            ja: "羽生" },
  "132": { en: "Karuizawa",                        ja: "軽井沢" },
  "133": { en: "Westland",                         ja: "ウエストランド" },
  "134": { en: "Paul John",                        ja: "ポールジョン" },
  "135": { en: "Loch Lomond (Inchmoan)",           ja: "ロッホローモンド（インチモーン）" },
  "136": { en: "Eden Mill",                        ja: "エデンミル" },
  "137": { en: "St. George's (The English Whisky Co.)", ja: "セント・ジョージ（イングリッシュウイスキー）" },
  "138": { en: "Nantou",                           ja: "南投" },
  "139": { en: "Kavalan",                          ja: "カバラン" },
  "140": { en: "Balcones",                         ja: "バルコーンズ" },
  "141": { en: "Fary Lochan",                      ja: "ファリーロッホン" },
  "142": { en: "Breuckelen Distilling",            ja: "ブルックリン・ディスティリング" },
  "143": { en: "Copperworks Distilling Co.",       ja: "コッパーワークス" },
  "144": { en: "High Coast (Box Whisky)",          ja: "ハイコースト（ボックスウイスキー）" },
  "145": { en: "Smögen Whisky",                    ja: "スモーゲン" },
  "146": { en: "Cotswolds",                        ja: "コッツウォルズ" },
  "147": { en: "Archie Rose",                      ja: "アーチー・ローズ" },
  "148": { en: "Starward",                         ja: "スターワード" },
  "149": { en: "Ardnamurchan",                     ja: "アードナムルッカン" },
  "150": { en: "West Cork Distillers",             ja: "ウエストコーク" },
  "151": { en: "Mackmyra",                         ja: "マックミラ" },
  "152": { en: "Shelter Point",                    ja: "シェルターポイント" },
  "153": { en: "Thy Whisky",                       ja: "ティ・ウイスキー" },
  "154": { en: "Mosgaard Whisky",                  ja: "モスゴール" },
  "155": { en: "Milk & Honey",                     ja: "ミルク＆ハニー" },
  "156": { en: "Glasgow Distillery Co.",           ja: "グラスゴー・ディスティラリー" },
  "157": { en: "Armorik (Warenghem)",              ja: "アルモリック（ワランゲム）" },
  "158": { en: "Yuza",                             ja: "遊佐" },
  "159": { en: "Mars Shinshu",                     ja: "マルス信州" },
  "160": { en: "Tsunuki",                          ja: "津貫" },
  "161": { en: "Nc'nean",                          ja: "ニクニアン" },
  "162": { en: "Isle of Raasay",                   ja: "アイル・オブ・ラーセイ" },
  "163": { en: "Isle of Harris",                   ja: "アイル・オブ・ハリス" },
  "164": { en: "Penderyn (Double Distilled)",      ja: "ペンダーリン（ダブルディスティルド）" },
  "165": { en: "Wolfburn (peated)",                ja: "ウルフバーン（ピート）" },

  // ── グレーンウイスキー (G prefix) ──────────────────────
  "G1":  { en: "North British",             ja: "ノースブリティッシュ" },
  "G2":  { en: "Carsebridge",               ja: "カースブリッジ" },
  "G3":  { en: "Caledonian",                ja: "カレドニアン" },
  "G4":  { en: "Cameronbridge",             ja: "キャメロンブリッジ" },
  "G5":  { en: "Invergordon",               ja: "インバーゴードン" },
  "G6":  { en: "Port Dundas",               ja: "ポートダンダス" },
  "G7":  { en: "Girvan",                    ja: "ガーヴァン" },
  "G8":  { en: "Cambus",                    ja: "キャンバス" },
  "G9":  { en: "Loch Lomond (Grain)",       ja: "ロッホローモンド（グレーン）" },
  "G10": { en: "Strathclyde",               ja: "ストラスクライド" },
  "G11": { en: "Nikka (Coffey Grain)",      ja: "ニッカ（コフィーグレーン）" },
  "G12": { en: "Nikka (Coffey Malt)",       ja: "ニッカ（コフィーモルト）" },
  "G13": { en: "Chita",                     ja: "知多" },
  "G14": { en: "Dumbarton",                 ja: "ダンバートン" },
  "G15": { en: "Loch Lomond (Rhosdhu)",      ja: "ロッホローモンド（ローズデュー）" },
  "G16": { en: "Glasgow Distillery Co. (Grain)", ja: "グラスゴー・ディスティラリー（グレーン）" },
  "G17": { en: "Starlaw (Glen Turner Distillery Ltd)", ja: "スターロー（グレンターナー・ディスティラリー）" },

  // ── バーボン / アメリカン (B prefix) ──────────────────
  "B1":  { en: "Heaven Hill",              ja: "ヘブンヒル" },
  "B2":  { en: "Bernheim",                 ja: "バーンハイム" },
  "B3":  { en: "Rock Town",                ja: "ロックタウン" },
  "B4":  { en: "FEW Spirits",              ja: "FEWスピリッツ" },
  "B5":  { en: "Cascade Hollow",           ja: "カスケードホロウ" },
  "B6":  { en: "Finger Lakes Distilling",   ja: "フィンガーレイクス・ディスティリング" },
  "B7":  { en: "MGP (Midwest Grain Products)", ja: "MGP（ミッドウエスト・グレイン・プロダクツ）" },
  "B8":  { en: "Woodinville Whiskey Co.",   ja: "ウッディンヴィル・ウイスキー" },
};