/**
 * SMWS蒸留所コード → 蒸留所名 マッピング
 *
 * コード体系:
 *   数字のみ (1〜168) : シングルモルト
 *   G + 数字          : グレーンウイスキー
 *   B + 数字          : バーボン / アメリカンウイスキー
 *   RW + 数字         : ライウイスキー
 *   CW + 数字         : コーンウイスキー
 *   R + 数字          : ラム
 *   A + 数字          : アルマニャック
 *   C + 数字          : コニャック
 *   GN + 数字         : ジン
 *
 * 各エントリの構造:
 *   en: 英語名（公式表記）
 *   ja: 日本語名（カタカナ表記）
 */

/** @typedef {{ en: string, ja: string }} Distillery */
/** @type {Record<string, Distillery>} */
const DISTILLERIES = {
  // ── シングルモルト (1–50) ──────────────────────────────
  1: { en: "Glenfarclas", ja: "グレンファークラス" },
  2: { en: "The Glenlivet", ja: "ザ・グレンリベット" },
  3: { en: "Bowmore", ja: "ボウモア" },
  4: { en: "Highland Park", ja: "ハイランドパーク" },
  5: { en: "Auchentoshan", ja: "オーヘントッシャン" },
  6: { en: "Glen Deveron / Macduff", ja: "グレンデヴロン / マクダフ" },
  7: { en: "Longmorn", ja: "ロングモーン" },
  8: { en: "Tamdhu", ja: "タムドゥー" },
  9: { en: "Glen Grant", ja: "グレングラント" },
  10: { en: "Bunnahabhain", ja: "ブナハーブン" },
  11: { en: "Tomatin", ja: "トマーティン" },
  12: { en: "Benriach", ja: "ベンリアック" },
  13: { en: "Dalmore", ja: "ダルモア" },
  14: { en: "Talisker", ja: "タリスカー" },
  15: { en: "Glenfiddich", ja: "グレンフィディック" },
  16: { en: "Glenturret", ja: "グレンタレット" },
  17: { en: "Scapa", ja: "スキャパ" },
  18: { en: "Inchgower", ja: "インチガワー" },
  19: { en: "Glen Garioch", ja: "グレンギリー" },
  20: { en: "Inverleven", ja: "インバーレーブン" },
  21: { en: "Glenglassaugh", ja: "グレングラッサ" },
  22: { en: "Glenkinchie", ja: "グレンキンチー" },
  23: { en: "Bruichladdich", ja: "ブルックラディ" },
  24: { en: "The Macallan", ja: "ザ・マッカラン" },
  25: { en: "Rosebank", ja: "ローズバンク" },
  26: { en: "Clynelish", ja: "クライヌリッシュ" },
  27: { en: "Springbank", ja: "スプリングバンク" },
  28: { en: "Tullibardine", ja: "タリバーディン" },
  29: { en: "Laphroaig", ja: "ラフロイグ" },
  30: { en: "Glenrothes", ja: "グレンロセス" },
  31: { en: "Isle of Jura", ja: "アイル・オブ・ジュラ" },
  32: { en: "Edradour", ja: "エドラダワー" },
  33: { en: "Ardbeg", ja: "アードベッグ" },
  34: { en: "Tamnavulin", ja: "タムナヴーリン" },
  35: { en: "Glen Moray", ja: "グレンマレイ" },
  36: { en: "Benrinnes", ja: "ベンリネス" },
  37: { en: "Cragganmore", ja: "クラガンモア" },
  38: { en: "Caperdonich", ja: "ケイパードニック" },
  39: { en: "Linkwood", ja: "リンクウッド" },
  40: { en: "Balvenie", ja: "バルヴェニー" },
  41: { en: "Dailuaine", ja: "デイルユーエン" },
  42: { en: "Ledaig / Tobermory", ja: "レダイグ / トバモリー" },
  43: { en: "Port Ellen", ja: "ポートエレン" },
  44: { en: "Craigellachie", ja: "クレイゲラキ" },
  45: { en: "Dallas Dhu", ja: "ダラスデュー" },
  46: { en: "Glenlossie", ja: "グレンロッシー" },
  47: { en: "Benromach", ja: "ベンロマック" },
  48: { en: "Balmenach", ja: "バルメナック" },
  49: { en: "Linlithgow / St Magdalene", ja: "リンリスゴー / セント・マグダレン" },
  50: { en: "Bladnoch", ja: "ブラッドノック" },

  // ── シングルモルト (51–100) ────────────────────────────
  51: { en: "Bushmills", ja: "ブッシュミルズ" },
  52: { en: "Old Pulteney", ja: "オールドプルトニー" },
  53: { en: "Caol Ila", ja: "カリラ" },
  54: { en: "Aberlour", ja: "アベラワー" },
  55: { en: "Royal Brackla", ja: "ロイヤルブラックラ" },
  56: { en: "Coleburn", ja: "コールバーン" },
  57: { en: "Glen Mhor", ja: "グレンモー" },
  58: { en: "Strathisla", ja: "ストラスアイラ" },
  59: { en: "Teaninich", ja: "ティーニニック" },
  60: { en: "Aberfeldy", ja: "アバフェルディ" },
  61: { en: "Brora", ja: "ブローラ" },
  62: { en: "Glenlochy", ja: "グレンロッキー" },
  63: { en: "Glentauchers", ja: "グレントーカーズ" },
  64: { en: "Mannochmore", ja: "マノックモア" },
  65: { en: "Imperial", ja: "インペリアル" },
  66: { en: "Ardmore", ja: "アードモア" },
  67: { en: "Banff", ja: "バンフ" },
  68: { en: "Blair Athol", ja: "ブレアアソル" },
  69: { en: "Glen Albyn", ja: "グレンアルビン" },
  70: { en: "Balblair", ja: "バルブレア" },
  71: { en: "Glenburgie / Glencraig", ja: "グレンバーギー / グレンクレイグ" },
  72: { en: "Miltonduff", ja: "ミルトンダフ" },
  73: { en: "Aultmore", ja: "オルトモア" },
  74: { en: "North Port", ja: "ノースポート" },
  75: { en: "Glenury", ja: "グレンユーリー" },
  76: { en: "Mortlach", ja: "モートラック" },
  77: { en: "Glen Ord / Glenordie", ja: "グレンオード / グレンオーディ" },
  78: { en: "Ben Nevis", ja: "ベンネヴィス" },
  79: { en: "Deanston", ja: "ディーンストン" },
  80: { en: "Glen Spey", ja: "グレンスペイ" },
  81: { en: "Glen Keith", ja: "グレンキース" },
  82: { en: "Glencadam", ja: "グレンカダム" },
  83: { en: "Convalmore", ja: "コンヴァルモア" },
  84: { en: "Glendullan", ja: "グレンダラン" },
  85: { en: "Glen Elgin", ja: "グレンエルギン" },
  86: { en: "Glenesk", ja: "グレンエスク" },
  87: { en: "Millburn", ja: "ミルバーン" },
  88: { en: "Speyburn", ja: "スペイバーン" },
  89: { en: "Tomintoul", ja: "トミントール" },
  90: { en: "Pittyvaich", ja: "ピティヴェイク" },
  91: { en: "Dufftown", ja: "ダフタウン" },
  92: { en: "Lochside", ja: "ロッホサイド" },
  93: { en: "Glen Scotia", ja: "グレンスコシア" },
  94: { en: "Fettercairn", ja: "フェッターケアン" },
  95: { en: "Auchroisk", ja: "オークロイスク" },
  96: { en: "Glendronach", ja: "グレンドロナック" },
  97: { en: "Littlemill", ja: "リトルミル" },
  98: { en: "Loch Lomond", ja: "ロッホローモンド" },
  99: { en: "Glenugie", ja: "グレンユーギー" },
  100: { en: "Strathmill", ja: "ストラスミル" },

  // ── シングルモルト (101–168) ───────────────────────────
  101: { en: "Knockando", ja: "ノッカンドゥー" },
  102: { en: "Dalwhinnie", ja: "ダルウィニー" },
  103: { en: "Royal Lochnagar", ja: "ロイヤルロッホナガー" },
  104: { en: "Glen Craig", ja: "グレンクレイグ" },
  105: { en: "Tormore", ja: "トーモア" },
  106: { en: "Cardhu", ja: "カードゥー" },
  107: { en: "Glenallachie", ja: "グレンアラヒー" },
  108: { en: "Allt-a'Bhainne", ja: "オルタヴァイン" },
  109: { en: "Mosstowie", ja: "モストウィー" },
  110: { en: "Oban", ja: "オーバン" },
  111: { en: "Lagavulin", ja: "ラガヴーリン" },
  112: { en: "Inchmurrin", ja: "インチマリン" },
  113: { en: "Braeval / Braes of Glenlivet", ja: "ブレイヴァル / ブレイズ・オブ・グレンリベット" },
  114: { en: "Longrow", ja: "ロングロウ" },
  115: { en: "Knockdhu", ja: "ノックドゥー" },
  116: { en: "Yoichi", ja: "余市" },
  117: { en: "Cooley", ja: "クーリー" },
  118: { en: "Connemara", ja: "コネマラ" },
  119: { en: "Yamazaki", ja: "山崎" },
  120: { en: "Hakushu", ja: "白州" },
  121: { en: "Isle of Arran", ja: "アイル・オブ・アラン" },
  122: { en: "Croftengea", ja: "クロフテンギア" },
  123: { en: "Glengoyne", ja: "グレンゴイン" },
  124: { en: "Miyagikyo", ja: "宮城峡" },
  125: { en: "Glenmorangie", ja: "グレンモーレンジィ" },
  126: { en: "Hazelburn", ja: "ヘーゼルバーン" },
  127: { en: "Port Charlotte", ja: "ポートシャーロット" },
  128: { en: "Penderyn", ja: "ペンダーリン" },
  129: { en: "Kilchoman", ja: "キルホーマン" },
  130: { en: "Chichibu", ja: "秩父" },
  131: { en: "Hanyu", ja: "羽生" },
  132: { en: "Karuizawa", ja: "軽井沢" },
  133: { en: "Westland", ja: "ウエストランド" },
  134: { en: "Paul John", ja: "ポールジョン" },
  135: { en: "Loch Lomond (Inchmoan)", ja: "ロッホローモンド（インチモーン）" },
  136: { en: "Eden Mill", ja: "エデンミル" },
  137: { en: "St. George's (The English Whisky Co.)", ja: "セント・ジョージ（イングリッシュウイスキー）" },
  138: { en: "Nantou", ja: "南投" },
  139: { en: "Kavalan", ja: "カバラン" },
  140: { en: "Balcones", ja: "バルコーンズ" },
  141: { en: "Fary Lochan", ja: "ファリーロッホン" },
  142: { en: "Breuckelen Distilling", ja: "ブルックリン・ディスティリング" },
  143: { en: "Copperworks Distilling Co.", ja: "コッパーワークス" },
  144: { en: "High Coast Distillery (formerly Box Whisky)", ja: "ハイコースト（旧ボックスウイスキー）" },
  145: { en: "Smögen Whisky", ja: "スモーゲン" },
  146: { en: "Cotswolds", ja: "コッツウォルズ" },
  147: { en: "Archie Rose", ja: "アーチー・ローズ" },
  148: { en: "Starward", ja: "スターワード" },
  149: { en: "Ardnamurchan", ja: "アードナムルッカン" },
  150: { en: "West Cork Distillers", ja: "ウエストコーク" },
  151: { en: "Mackmyra", ja: "マックミラ" },
  152: { en: "Shelter Point", ja: "シェルターポイント" },
  153: { en: "Thy Whisky", ja: "ティ・ウイスキー" },
  154: { en: "Mosgaard Whisky", ja: "モスゴール" },
  155: { en: "Milk & Honey Distillery", ja: "ミルク＆ハニー" },
  156: { en: "Glasgow Distillery", ja: "グラスゴー・ディスティラリー" },
  157: { en: "Warenghem Distillery (Armorik)", ja: "ワランゲム（アルモリック）" },
  158: { en: "Yuza", ja: "遊佐" },
  159: { en: "Mars Komagatake Distillery", ja: "マルス駒ヶ岳蒸留所" },
  160: { en: "Mars Tsunuki Distillery", ja: "マルス津貫蒸留所" },
  161: { en: "Nc'nean Distillery", ja: "ニクニアン" },
  162: { en: "Isle of Raasay", ja: "アイル・オブ・ラーセイ" },
  163: { en: "Isle of Harris Distillery", ja: "アイル・オブ・ハリス" },
  164: { en: "Penderyn (double distilled)", ja: "ペンダーリン（ダブルディスティルド）" },
  165: { en: "Wolfburn (peated)", ja: "ウルフバーン（ピート）" },
  166: { en: "Torabhaig Distillery", ja: "トラベイグ" },
  167: { en: "Clydeside Distillery", ja: "クライドサイド" },
  168: { en: "InchDairnie Distillery (KinGlassie)", ja: "インチデアーニー（キングラッシー）" },

  // ── グレーンウイスキー (G prefix) ──────────────────────
  G1: { en: "North British", ja: "ノースブリティッシュ" },
  G2: { en: "Carsebridge", ja: "カースブリッジ" },
  G3: { en: "Caledonian", ja: "カレドニアン" },
  G4: { en: "Cameronbridge", ja: "キャメロンブリッジ" },
  G5: { en: "Invergordon", ja: "インバーゴードン" },
  G6: { en: "Port Dundas", ja: "ポートダンダス" },
  G7: { en: "Girvan", ja: "ガーヴァン" },
  G8: { en: "Cambus", ja: "キャンバス" },
  G9: { en: "Loch Lomond (Grain)", ja: "ロッホローモンド（グレーン）" },
  G10: { en: "Strathclyde", ja: "ストラスクライド" },
  G11: { en: "Nikka Coffey Grain", ja: "ニッカ・コフィーグレーン" },
  G12: { en: "Nikka Coffey Malt", ja: "ニッカ・コフィーモルト" },
  G13: { en: "Chita", ja: "知多" },
  G14: { en: "Dumbarton", ja: "ダンバートン" },
  G15: { en: "Loch Lomond (Rhosdhu)", ja: "ロッホローモンド（ローズデュー）" },
  G16: { en: "Glasgow Distillery", ja: "グラスゴー・ディスティラリー（グレーン）" },
  G17: { en: "Starlaw (Glen Turner Distillery Ltd)", ja: "スターロー（グレンターナー・ディスティラリー）" },

  // ── バーボン / アメリカン (B prefix) ──────────────────
  B1: { en: "Heaven Hill", ja: "ヘブンヒル" },
  B2: { en: "New Bernheim", ja: "ニュー・バーンハイム" },
  B3: { en: "Rock Town", ja: "ロックタウン" },
  B4: { en: "FEW Spirits", ja: "FEWスピリッツ" },
  B5: { en: "George Dickel (Cascade Hollow)", ja: "ジョージ・ディッケル（カスケードホロウ）" },
  B6: { en: "Finger Lakes Distilling", ja: "フィンガーレイクス・ディスティリング" },
  B7: { en: "MGP (Midwest Grain Products)", ja: "MGP（ミッドウエスト・グレイン・プロダクツ）" },
  B8: { en: "Woodinville Whiskey Co.", ja: "ウッディンヴィル・ウイスキー" },
  B9: { en: "Wilderness Trail Distillery", ja: "ワイルダネス・トレイル・ディスティラリー" },

  // ── ライウイスキー (RW prefix) ─────────────────────────
  RW1: { en: "FEW Spirits", ja: "FEWスピリッツ" },
  RW2: { en: "Finger Lakes Distilling", ja: "フィンガーレイクス・ディスティリング" },
  RW3: { en: "New York Distilling Co.", ja: "ニューヨーク・ディスティリング" },
  RW4: { en: "Unknown", ja: "不明" },
  RW5: { en: "Lux Row Distillers / MGP", ja: "ラックスロウ / MGP" },
  RW6: { en: "Kyrö Distillery Company", ja: "キュロ・ディスティラリー" },
  RW7: { en: "Journeyman Distillery", ja: "ジャーニーマン・ディスティラリー" },
  RW8: { en: "Catoctin Creek Distilling Co.", ja: "カトクティン・クリーク・ディスティリング" },
  RW9: { en: "Wilderness Trail Distillery", ja: "ワイルダネス・トレイル・ディスティラリー" },

  // ── コーンウイスキー (CW prefix) ───────────────────────
  CW1: { en: "Heaven Hill Distillery", ja: "ヘブンヒル" },
  CW2: { en: "Balcones", ja: "バルコーンズ" },

  // ── ラム (R prefix) ────────────────────────────────────
  R1: { en: "Monymusk", ja: "モニマスク" },
  R2: { en: "Demerara Distillers (El Dorado)", ja: "デメララ・ディスティラーズ（エル・ドラード）" },
  R3: { en: "West Indies Rum", ja: "ウエスト・インディーズ・ラム" },
  R4: { en: "Trinidad Distillers (Angostura)", ja: "トリニダード・ディスティラーズ（アンゴスチュラ）" },
  R5: { en: "Long Pond", ja: "ロング・ポンド" },
  R6: { en: "Foursquare", ja: "フォースクエア" },
  R7: { en: "Hampden", ja: "ハンプデン" },
  R8: { en: "Compañía Licorera de Nicaragua (Flor de Caña)", ja: "コンパニーア・リコレーラ・デ・ニカラグア（フロール・デ・カーニャ）" },
  R9: { en: "Varela Hermanos (Ron Abuelo)", ja: "バレラ・エルマノス（ロン・アブエロ）" },
  R10: { en: "Trinidad Distiller's", ja: "トリニダード・ディスティラーズ" },
  R11: { en: "Worthy Park", ja: "ワージー・パーク" },
  R12: { en: "Travellers", ja: "トラベラーズ" },
  R13: { en: "Caroni", ja: "カロニ" },
  R14: { en: "Uitvlugt", ja: "アウトフルフト" },

  // ── アルマニャック (A prefix) ──────────────────────────
  A1: { en: "Chateau de Lacaze", ja: "シャトー・ド・ラカーズ" },
  A2: { en: "Domaine Laguille", ja: "ドメーヌ・ラギーユ" },
  A3: { en: "J. Goudoulin (Veuve Goudoulin)", ja: "J.グードゥラン（ヴーヴ・グードゥラン）" },
  A4: { en: "Domaine d'Espérance", ja: "ドメーヌ・デスペランス" },
  A5: { en: "Chateau de Laubade", ja: "シャトー・ド・ローバード" },
  A6: { en: "Domaine Lasalle", ja: "ドメーヌ・ラサール" },
  A7: { en: "Domaine Lasalle", ja: "ドメーヌ・ラサール" },
  A8: { en: "Domaine de Cavaillon", ja: "ドメーヌ・ド・カヴァイヨン" },
  A9: { en: "Domaine de Saurine", ja: "ドメーヌ・ド・ソーリン" },

  // ── コニャック (C prefix) ──────────────────────────────
  C1: { en: "Camus", ja: "カミュ" },
  C2: { en: "Domaine de Chez Guérive", ja: "ドメーヌ・ド・シェ・ゲリーヴ" },
  C3: { en: "Louis Royer", ja: "ルイ・ロワイエ" },
  C4: { en: "Distillery D'Aumagne", ja: "ディスティルリー・ドーマーニュ" },
  C5: { en: "Tiffon Cognac", ja: "ティフォン" },
  C6: { en: "M & H Bonneau", ja: "M＆H ボノー" },
  C7: { en: "Guy Rateau PC", ja: "ギー・ラトー" },
  C8: { en: "Marie C Bodit GC", ja: "マリー・C・ボディ" },
  C9: { en: "Robert Audebeau PC", ja: "ロベール・オードボー" },

  // ── ジン (GN prefix) ───────────────────────────────────
  GN1: { en: "Glasgow Distillery Company", ja: "グラスゴー・ディスティラリー" },
  GN2: { en: "Strathearn Distillers", ja: "ストラスアーン・ディスティラーズ" },
  GN3: { en: "Borders Distillery", ja: "ボーダーズ・ディスティラリー" },
  GN4: { en: "Boatyard Distillery", ja: "ボートヤード・ディスティラリー" },
  GN5: { en: "Glenrinnes Distillery", ja: "グレンリネス・ディスティラリー" },
  GN6: { en: "Holyrood Distillery", ja: "ホリールード・ディスティラリー" },
  GN7: { en: "Cotswolds", ja: "コッツウォルズ" },
};
